require("vim._core.ui2").enable()

require("options")
require("keymaps")

require("plugins.ui")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.blink")
require("plugins.yazi")
require("plugins.fzf")
require("plugins.lazygit")
require("plugins.mini")
require("plugins.toggleterm")
require("plugins.copilot")
