mode = fill
splash = false

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/mxpadidar/.config/hypr/new-dark.jpg
#     fit_mode = fill
# }

wallpaper {
    monitor = eDP-1
    path = /home/mxpadidar/.config/hypr/new-dark.jpg
    fit_mode = fill
}
