splash = false

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/dark-bg.jpg
    fit_mode = fill
}


wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/dark-bg.jpg
    fit_mode = fill
}

